conaticus/boolean

package-lock.json
package.json
src/deploy-commands.ts
src/events/messageReactionRemove.ts
src/files.ts
src/index.ts

Using `process.cwd()`, `__dirname` and `path.join()` is the best way of handling files that works everywhere.

Replaced relative paths with a better way of handling files 

---

src/commands/math.ts

```
/math 5+5
/math 11 inches in meters
/math 20 beerbarrels in liters
```
gang 😎 
(note: it doesn't use eval and it's safe)

Add math command

---

package-lock.json
package.json
src/commands/announce.ts
src/config.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts
src/events/ready.ts
src/utils.ts

I added mathjs as a dependency with the reason of SpeckyYTs pr with a math command and also added getData and writeData functions, which will make it easier to deal with, but primarily if we'd switch to a database in the future it'd be quite easy
I also fixed a bug I introduced earlier being that the reaction events will now get the ids directly from data.json instead of getting it from config.ts

Mathjs and json functions

---

package.json
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/interactionCreate.ts
src/events/messageCreate.ts
src/events/messageDelete.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts
src/events/messageUpdate.ts
src/events/ready.ts
src/structures/Bot.ts
src/types.ts

I made a typo in the commit message, it's `Event Handler` not `Command Handler`
Close #16

feat: Better event handler

---

package.json
src/commands/announce.ts
src/config.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/messageCreate.ts
src/events/messageDelete.ts
src/events/messageUpdate.ts
src/events/ready.ts
src/files.ts
src/logger/Logger.ts
src/structures/Bot.ts
src/utils.ts

Added new logger, check out
https://npmjs.com/package/pino
Config references the same as well.

Logger 2.0, Config 2.0

---

src/config.ts
src/events/guildMemberAdd.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/interactionCreate.ts
src/events/messageCreate.ts
src/events/messageDelete.ts
src/events/messageReactionAdd.ts
src/events/messageReactionRemove.ts
src/events/messageUpdate.ts
src/events/ready.ts
src/structures/Bot.ts
src/types.ts

Logger made public on client, meaning that we don't have to have ugly events like this: async run(_, __, actualstuffwewant) {
Also removed some unesscary variables and improved config.ts to actually use the IBotConfig interface
Edit: I also fixed commands not registering properly

Logger made public on client, improved config.ts

---

.env.example
package.json
src/commands/verbal.ts
src/config.ts
src/events/guildMemberAdd.ts

I added the verbal command to warn users. 
I don't know why the captcha doesn't work but the rest does.
Add warnChannelId in config.ts.

Verbal command added

---

__tests__/mock.test.ts
__tests__/utils.test.ts
jest.config.ts
package.json

This is some basic tests, i have no experience with jest, but it still get the job done,
Any jest expert can yell at me for doing this.

test: Added some jest test

---

src/commands/deleteSuggestion.ts

Only delete suggestions in a thread inside suggestions channel based on #74

delete suggestions command

---

src/events/messageCreate.ts

Added more bad words

---

src/commands/verbal.ts
src/events/ready.ts

fix: Command not registering

---

src/index.ts
src/structures/Bot.ts

The client options Object is useless in constructor options, I think this is better to put this directly in super() directly instead of use constructor option

Remove useless Bot constructor options

---

src/events/messageCreate.ts

self explanatory and very simple change

feat(automod): timeout members for mass mentioning

---

src/commands/announce.ts

Improved the announce command to use Discord modals now that they're supported

---

.github/workflows/CI.yaml
src/commands/announce.ts
src/commands/clear.ts
src/commands/config.ts
src/commands/deleteSuggestion.ts
src/commands/deny.ts
src/commands/ping.ts
src/commands/quiz.ts
src/commands/repeat.ts
src/commands/roleme.ts
src/commands/selfrole.ts
src/commands/suggest.ts
src/commands/user.ts
src/commands/verbal.ts
src/database/badges.ts
src/database/index.ts
src/database/selfroles.ts
src/events/guildMemberRemove.ts
src/events/guildMemberUpdate.ts
src/events/messageCreate.ts
src/events/messageDelete.ts
src/events/messageUpdate.ts
src/events/ready.ts
src/files.ts
src/index.ts
src/structures/Bot.ts
src/structures/BotCommand.ts
src/structures/Logger.ts
src/structures/index.ts
src/utils.ts

Enforce Linter Rules

---

src/commands/suggest.ts

Allowed attachments in suggestions

---

src/commands/verbal.ts
src/events/guildMemberUpdate.ts

* The colours were changed as per conaticus request
* If the time out duration is less than 10 minutes the appeal button will only last for as long as the time out

Changed appeal embed colour + Limited time out appeal button time

---

jest.config.js
src/commands/ping.ts

Fix Jest Config

---

src/commands/verbal.ts
src/database/channels.ts

Makes it so that warnings are sent to the channel they are created in.
Solves #136.

Update Warn Command

---

src/commands/user.ts

Updates user command so another user can be specified.

Update User Command

---

src/commands/warn.ts

ref(verbal): branded "verbal" to just "warnings"

---

src/events/messageDelete.ts

Fixing deleted messages executor tracking

---

package.json
src/database/channels.ts
src/events/messageCreate.ts
src/events/messageUpdate.ts
src/utils.ts

- The bot will create a thread on a message in the help channel if a message is sent
- Remove bad content filter - discord handles this for us now
closes #157
closes #152

Create thread when message is sent in help channel

---

src/events/messageCreate.ts

Updated import order so that ESLint stops breaking CI checks.

ref(lint): fixed import order

---

src/files.ts

Made improvement to files file to fix code logic error
